name: LorraineJug
description: Lorraine Java User Group
url: http://www.lorrainejug.org
exclude: [README.md, _site/, jekyll-deploy.sh, stasher.sh, config-parser.sh, lorrainejug-site.iml]
gems: [jekyll-sass]
markdown: redcarpet
pygments: true
baseurl: /lorrainejug-site
paginate: 5
paginate_path: events/:num
sass:
    style: expanded           # nested|expanded|compact|compressed
    deploy_style: compressed  # nested|expanded|compact|compressed
    compile_in_place: false   # true|false
